services:
  platform-training-angular:
    container_name: platform-training-angular
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_URL: $API_URL
    environment:
        API_URL: $API_URL
    ports:
      - "4202:4202"

networks:
  platform-training-net:
    external: true