services:
  platform-training-angular:
    container_name: platform-training-angular
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4201:4201"

networks:
  platform-training-net:
    external: true